graph TD;

request((POST request));
request -- activates --> router;
router-- forwards to --> validators;
validators -- success --> auth;
validators -- failure --> error;
auth -- success --> controller;
auth -- failure --> error((error response));
controller -- creates --> db((mongoose query));
db -- success --> pubsub((PubSub update));
db -- success --> success((success response));
db -- failure --> error;
pubsub -- failure --> pubsub;
